/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.text.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Christopher McDaniel
 */
public class TaxProgramJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TaxProgramJFrame
     */
    public TaxProgramJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Income = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Dependents = new javax.swing.JLabel();
        MStatus = new javax.swing.JLabel();
        PPeriods = new javax.swing.JLabel();
        FedTax = new javax.swing.JLabel();
        SSTax = new javax.swing.JLabel();
        MedTax = new javax.swing.JLabel();
        NetPay = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        DepTxt = new javax.swing.JTextField();
        IncomeTxt = new javax.swing.JTextField();
        MStatusCombo = new javax.swing.JComboBox<>();
        PayPeriodsCombo = new javax.swing.JComboBox<>();
        FedTaxTxt = new javax.swing.JTextField();
        SSTaxTxt = new javax.swing.JTextField();
        MedTaxTxt = new javax.swing.JTextField();
        NetPayTxt = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Income.setText("Income");

        Name.setText("Name of User");

        Dependents.setText("Dependents");

        MStatus.setText("Maritial Status");

        PPeriods.setText("Pay Periods");

        FedTax.setText("Federal Tax");

        SSTax.setText("Social Security Tax");

        MedTax.setText("Medical Tax");

        NetPay.setText("Net Pay");

        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });

        DepTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepTxtActionPerformed(evt);
            }
        });

        IncomeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomeTxtActionPerformed(evt);
            }
        });

        MStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Single", "Married" }));
        MStatusCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MStatusComboActionPerformed(evt);
            }
        });

        PayPeriodsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Bi-weekly", "Monthly" }));
        PayPeriodsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayPeriodsComboActionPerformed(evt);
            }
        });

        FedTaxTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FedTaxTxtActionPerformed(evt);
            }
        });

        SSTaxTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSTaxTxtActionPerformed(evt);
            }
        });

        MedTaxTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedTaxTxtActionPerformed(evt);
            }
        });

        NetPayTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetPayTxtActionPerformed(evt);
            }
        });

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("$");

        jLabel2.setText("$");

        jLabel3.setText("$");

        jLabel4.setText("$");

        jLabel5.setText("$");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Tax Program Calculator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dependents)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Income)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addComponent(MStatus)
                                    .addComponent(PPeriods))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubmitBtn)
                                .addGap(65, 65, 65)
                                .addComponent(ExitBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(MStatusCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(DepTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IncomeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PayPeriodsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(NetPay)
                                                .addGap(112, 112, 112))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(MedTax)
                                                    .addComponent(SSTax)
                                                    .addComponent(FedTax))
                                                .addGap(33, 33, 33)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MedTaxTxt))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NetPayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(FedTaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(SSTaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name)
                            .addComponent(jLabel6))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FedTaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(FedTax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSTaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(SSTax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MedTaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(MedTax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NetPayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(NetPay)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(Income))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DepTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dependents))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MStatus))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PayPeriodsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PPeriods))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitBtn)
                    .addComponent(ExitBtn))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        
        //variables
        double grossPay = 0;
        double dep = 0;
        
        double SSPCT = 0.062;
        double MEDPCT = 0.0145;
        double BWith = 155.80;
        double MWith = 337.50;

        double fedTax = 0;
        double ssTax = 0;
        double medTax = 0;
        double netPay = 0;  
        
        //array
        double[] SBBase = new double[] { 0, 0, 35.90, 201.05, 719.80, 1794.16, 4650.31, 4673.41 };
        double[] SBMax = new double[] { 88, 447, 1548, 3623, 7460, 16115, 16181, 0 };
        double[] SBPct = new double[] { 0, 0.10, 0.15, 0.25, 0.28, 0.33, 0.35, 0.396 };
 
        double[] SMBase = new double[] { 0, 0, 77.70, 435.45, 1559.45, 3887.09, 10075.91, 10125.26 };
        double[] SMMax = new double[] { 192, 969, 3354, 7850, 16163, 34917, 35058, 0 };
        double[] SMPct = new double[] { 0, 0.10, 0.15, 0.25, 0.28, 0.33, 0.35, 0.396 };

        double[] MBBase = new double[] { 0, 0, 71.70, 402, 1144.25, 2008.61, 4335.77, 5062.72 };
        double[] MBMax = new double[] { 333, 1050, 3252, 6221, 9308, 16360, 18437, 0 };
        double[] MBPct = new double[] { 0, 0.10, 0.15, 0.25, 0.28, 0.33, 0.35, 0.396 };
       
        double[] MMBase = new double[] { 0, 0, 155.40, 871.05, 2479.30, 4351.94, 9394.01, 10969.01 };
        double[] MMMax = new double[] { 721, 2275, 7046, 13479, 20167, 35446, 39946, 0 };
        double[] MMPct = new double[] { 0, 0.10, 0.15, 0.25, 0.28, 0.33, 0.35, 0.396 };               
        
        //Input
        grossPay = Double.parseDouble(IncomeTxt.getText());
        dep = Double.parseDouble(DepTxt.getText()); 

                //Process
                if (MStatusCombo.getSelectedIndex() == 1)    // single
                {
                    if (PayPeriodsCombo.getSelectedIndex() == 1)   // biweekly
                    {
                        fedTax = CalcFedTax(dep, BWith, grossPay, SBBase, SBMax, SBPct);                       
                    }
                    else   
                    {                           
                        fedTax = CalcFedTax(dep, MWith, grossPay, SMBase, SMMax, SMPct);                       
                    }
                }
                else // married
                {
                    if (PayPeriodsCombo.getSelectedIndex() == 1)   // biweekly
                    {
                        fedTax = CalcFedTax(dep, BWith, grossPay, MBBase, MBMax, MBPct);
                    }
                    else    //monthly
                    {                                                
                        fedTax = CalcFedTax(dep, MWith, grossPay, MMBase, MMMax, MMPct);                   
                    }    
                }                              
            

            ssTax = grossPay * SSPCT;
            medTax = grossPay * MEDPCT;
            netPay = grossPay - fedTax - ssTax - medTax;
               
            //Output
            DecimalFormat df = new DecimalFormat("##.00");
            
            FedTaxTxt.setText(df.format(fedTax));
            SSTaxTxt.setText(df.format(ssTax));
            MedTaxTxt.setText(df.format(medTax));
            NetPayTxt.setText(df.format(netPay));
   
    }//GEN-LAST:event_SubmitBtnActionPerformed
   
    private void MStatusComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MStatusComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MStatusComboActionPerformed

    private void PayPeriodsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayPeriodsComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayPeriodsComboActionPerformed

    private void FedTaxTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FedTaxTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FedTaxTxtActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void IncomeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeTxtActionPerformed
        DecimalFormat df = new DecimalFormat("##.00");
        double grossPay = Double.parseDouble(IncomeTxt.getText());
        IncomeTxt.setText(df.format(grossPay));
    }//GEN-LAST:event_IncomeTxtActionPerformed

    private void DepTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepTxtActionPerformed

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed

    private void SSTaxTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSTaxTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSTaxTxtActionPerformed

    private void MedTaxTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedTaxTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedTaxTxtActionPerformed
 
    static double CalcFedTax(double dep, double grossPay, double withDepAmt, double[] Base, double[] Max, double[] Pct)
    {
        double withholding = 0;
        double taxablePay = 0;
        double fedTax = 0;

        withholding = dep * grossPay;
        taxablePay = withDepAmt - withholding;

        if (taxablePay <= Max[0])   //Level 1
        {
            fedTax = 0;
        }
        else if (taxablePay <= Max[1])    //Level 2
        {
            fedTax = Base[1] + (Pct[1] * (taxablePay - Max[0]));
        }
        else if (taxablePay <= Max[2])    //Level 3
        {
            fedTax = Base[2] + (Pct[2] * (taxablePay - Max[1]));
        }
        else if (taxablePay <= Max[3])    //Level 4
        {
            fedTax = Base[3] + (Pct[3] * (taxablePay - Max[2]));
        }
        else if (taxablePay <= Max[4])    //Level 5
        {
            fedTax = Base[4] + (Pct[4] * (taxablePay - Max[3]));
        }
        else if (taxablePay <= Max[5])    //Level 6
        {
            fedTax = Base[5] + (Pct[5] * (taxablePay - Max[4]));
        }
        else if (taxablePay <= Max[6])    //Level 7
        {
            fedTax = Base[6] + (Pct[6] * (taxablePay - Max[5]));
        }
        else    //Level 8
        {
            fedTax = Base[7] + (Pct[7] * (taxablePay - Max[6]));
        }

        return fedTax;
    }
 
    private void NetPayTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetPayTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NetPayTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxProgramJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxProgramJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxProgramJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxProgramJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaxProgramJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DepTxt;
    private javax.swing.JLabel Dependents;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel FedTax;
    private javax.swing.JTextField FedTaxTxt;
    private javax.swing.JLabel Income;
    private javax.swing.JTextField IncomeTxt;
    private javax.swing.JLabel MStatus;
    private javax.swing.JComboBox<String> MStatusCombo;
    private javax.swing.JLabel MedTax;
    private javax.swing.JTextField MedTaxTxt;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel NetPay;
    private javax.swing.JTextField NetPayTxt;
    private javax.swing.JLabel PPeriods;
    private javax.swing.JComboBox<String> PayPeriodsCombo;
    private javax.swing.JLabel SSTax;
    private javax.swing.JTextField SSTaxTxt;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
